#import dna sequence
Seq = "ACTAGCGGCAGTATAGGTCCCGGAAGCAACCTTTAGGCAGATCAAGAAGCTTGCCAAGGCCTGTGCACTCTTCGTTCGCTATTAGCATGTGGTTTTACCTCCTCAACGTTCGTTTTGAAGATGACTGTATGTGAGATTTTGGGGCACACGGACGACCTCGAATCCACTCGGCGAATCCGGCCTTATAAAAGAACGCCCGCATTGTGGCGCAGAACCTGTGCCCAGGGCGTTGCATACGGACTTAGGTCGTCCCCCAACTGGTCCATCATCGACCGGTTGTGAATAGCTACCGCGGAGGGCTCATCAGTCCCAAGAAAGCCTACCCGCCTCACTGTGGGGTATGCTTTCTCCCTCTGGCTTTGCGAGTCCCCAGTCCTCTACTTTCGCTGTCGTGTTGAGGACATGGCAAGTATTGGGCACGGGTACATGGTTGTCGGCGCATCCTAGTAAGTTGCCGAATCTGTTCGACTCTCGTCATACCAGTGAGTTTAGGTTTCTGGCCGCCAAATCGTAATGACCATGATAAGGTGCAACGTCTCAATATGGACGCATCATCTGTATGAATTCATGCACTTTGTGGTGGCCATGTATTTATGCGTCCTCTATGGGAATTCACTTAAAGAGAATACTATCCAAAAGGGACCTCCTCTGTCATCCCGGGGCACGAATCGCGTGCTTACATGGAACACATGATTACGCGGGGTAAGACCAGTTTATGAAATTGACATTCCAAATCTGTGTAAGCTTATTTGAGCTGCACCGTTCAATTCGGTCGCCTTGCGTCGGCGGAGCTGGAGGAGATCGAATCCCATCGTGATTAGGTATCGGACTCTGACGATAATATACCGACCGGGCGGCGAATTTGTTCCCTCCCAGGCGGGCACTACGGTATTATGCTGTCCCTGTCCAGGAGAATACTCTACCGTATCGACAGTTGTGGGT"

#revert Seq function
rSeq = Seq[::-1]
#generate complement conversion loop
for i in rSeq:
    rcDNAA= i
    if(i=="A"): print("T", end="")
    elif(i=="T"): print("A", end="")
    elif(i=="G"): print("C", end="")
    elif(i=="C"): print("G", end="")
#erase the last extra artefact character of rcDNAA to rcDNA
rcDNA= rcDNAA[:-1]
#display rcDNA
print(rcDNA)